In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import csv
import math

In [2]:
# declare variables
num_files = 16
num_rows = 7
num_columns = 2
#kcal_conv = 627.5095 #kcal/mol per 1 hartree
rt = 298.15*(0.001987/627.5095) #kcal/mol

# declare arrays
raw_data = np.zeros((num_files, num_rows, num_columns))
#print(raw_data)
input_filename = []

directory = r'D3BJ_model1/csv/'
file_id = 0
for file in os.listdir(directory):
    full_path = os.path.abspath(directory)
    real_file = full_path + "\\" + file
    input_filename.append(file)

    results = []

    with open(real_file) as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|') 
        row_id = 0
        for row in reader:
            if (row_id > 0):
                raw_data [file_id][row_id-1][0] = row[4]
                raw_data [file_id][row_id-1][1] = row[5]
            row_id = row_id + 1
    file_id = file_id + 1
#print(input_filename)
#print(raw_data)

In [3]:
def eq_frac(input_file, input_row, input_column):
    #print(-raw_data[input_file][input_row][input_column]/rt)
    numerator = -raw_data[input_file][input_row][input_column]/rt
    denominator = 0
    for i in range (0, 16):
        denominator = denominator + np.exp((-raw_data[i][input_row][input_column]/rt)-numerator)
    return(1.0/denominator)

In [4]:
raw_output = np.zeros((num_files, num_rows, num_columns))
for file_id in range (0, 16):
    for row_id in range (0, 7):
        raw_output [file_id][row_id][0] = eq_frac(file_id, row_id, 0)
        raw_output [file_id][row_id][1] = eq_frac(file_id, row_id, 1)

for file_id in range (0,16):
    print(input_filename[file_id])
    print(raw_output[file_id])
    print("")
    pd.DataFrame(raw_output[file_id]).to_csv('D3BJ_model1/calc/%s' % input_filename[file_id])

D3BJ_model1_data_118.csv
[[4.41862549e-01 4.72188331e-01]
 [4.86596783e-01 1.50181560e-15]
 [2.44990083e-01 2.60997980e-01]
 [1.71541329e-01 1.51021884e-01]
 [2.47222863e-01 2.39888317e-01]
 [3.31541509e-01 3.99895752e-01]
 [5.38218536e-01 6.53861668e-01]]

D3BJ_model1_data_150.csv
[[1.77229856e-04 2.62614439e-06]
 [1.29536794e-04 7.21745197e-21]
 [1.31375616e-03 2.42518130e-05]
 [3.09299815e-04 6.54678677e-06]
 [2.35886463e-03 4.22187305e-05]
 [5.15862840e-05 1.27182317e-05]
 [8.67521872e-03 4.28566303e-05]]

D3BJ_model1_data_273.csv
[[5.93921422e-06 3.23804649e-07]
 [5.58558678e-06 1.01428552e-21]
 [2.17208545e-05 1.51440172e-06]
 [5.69119296e-06 3.73812498e-07]
 [2.88377188e-05 1.92843784e-06]
 [6.71549399e-05 1.59987295e-06]
 [1.18407680e-04 6.11401580e-06]]

D3BJ_model1_data_295.csv
[[1.46882239e-06 6.04527254e-07]
 [1.22035828e-06 1.62126812e-21]
 [1.58272301e-04 3.69700198e-06]
 [1.42747580e-04 9.90844644e-07]
 [2.18760789e-04 6.20760583e-06]
 [8.24747225e-05 1.76643187e-06]
 [2