In [102]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import csv
import math

In [117]:
# declare variables
num_files = 12
num_rows = 7
num_columns = 2
#kcal_conv = 627.5095 #kcal/mol per 1 hartree
rt = 298.15*(0.001987/627.5095) #kcal/mol

# declare arrays
raw_data = np.zeros((num_files, num_rows, num_columns))
#print(raw_data)
input_filename = []

directory = r'B3LYP_model4/csv/'
file_id = 0
for file in os.listdir(directory):
    full_path = os.path.abspath(directory)
    real_file = full_path + "\\" + file
    input_filename.append(file)

    results = []

    with open(real_file) as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|') 
        row_id = 0
        for row in reader:
            if (row_id > 0):
                raw_data [file_id][row_id-1][0] = row[4]
                raw_data [file_id][row_id-1][1] = row[5]
            row_id = row_id + 1
    file_id = file_id + 1
#print(input_filename)
#print(raw_data)

In [118]:
def eq_frac(input_file, input_row, input_column):
    #print(-raw_data[input_file][input_row][input_column]/rt)
    numerator = -raw_data[input_file][input_row][input_column]/rt
    denominator = 0
    for i in range (0, 12):
        denominator = denominator + np.exp((-raw_data[i][input_row][input_column]/rt)-numerator)
    return(1.0/denominator)

In [122]:
raw_output = np.zeros((num_files, num_rows, num_columns))
for file_id in range (0, 12):
    for row_id in range (0, 7):
        raw_output [file_id][row_id][0] = eq_frac(file_id, row_id, 0)
        raw_output [file_id][row_id][1] = eq_frac(file_id, row_id, 1)

for file_id in range (0,12):
    print(input_filename[file_id])
    print(raw_output[file_id])
    print("")
    pd.DataFrame(raw_output[file_id]).to_csv('B3LYP_model4/calc/%s' % input_filename[file_id])

B3LYP_model1_data_118.csv
[[0.35651494 0.48083373]
 [0.39823362 0.49736155]
 [0.1877801  0.25327479]
 [0.1295687  0.16336751]
 [0.16941984 0.22546795]
 [0.24326255 0.39026367]
 [0.39266172 0.60532272]]

B3LYP_model1_data_150.csv
[[4.41350187e-04 1.13760815e-05]
 [3.64921345e-04 1.03023929e-05]
 [2.96955301e-03 9.98277803e-05]
 [9.03545575e-04 3.02095646e-05]
 [5.60578190e-03 1.86829192e-04]
 [2.62452904e-03 6.04920643e-05]
 [7.77290288e-03 2.06272040e-04]]

B3LYP_model1_data_273.csv
[[1.84356531e-05 1.17576001e-06]
 [1.94893765e-05 1.22431752e-06]
 [6.22438676e-05 5.47109755e-06]
 [1.92830535e-05 1.45941811e-06]
 [7.50680900e-05 6.68940938e-06]
 [7.06350725e-05 6.29860684e-06]
 [2.36044539e-04 2.30206423e-05]]

B3LYP_model1_data_295.csv
[[1.51254468e-04 5.08282703e-06]
 [1.26125901e-04 4.52766735e-06]
 [5.81738881e-04 2.91674231e-05]
 [2.31159016e-04 8.45860047e-06]
 [8.57096478e-04 4.64204233e-05]
 [3.82599346e-04 1.54579950e-05]
 [8.90948685e-04 4.50240853e-05]]

B3LYP_model1_data_33